# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 20:49
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0015_auto_20161230_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttext',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
