# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0018_posttext_imgur_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttext',
            old_name='imgur_thumbnail',
            new_name='imgur_image',
        ),
    ]
