# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0020_auto_20170109_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttext',
            name='imgur_image',
        ),
    ]
