# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0022_posttext_vote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voting_direction',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
