# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0027_posttext_voted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
    ]
