# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0030_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
