# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0039_comments_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='children',
        ),
    ]
