# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('r', '0041_auto_20170204_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplies',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='r.Comments')),
                ('reply_body', models.TextField(verbose_name='')),
                ('reply_date', models.DateTimeField(auto_now_add=True)),
                ('reply_instance', models.IntegerField(default=0)),
                ('reply_author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('r.comments',),
        ),
    ]
