# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0045_auto_20170204_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='commentreplies',
            name='main_post',
        ),
        migrations.AddField(
            model_name='commentreplies',
            name='main_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='r.Comments'),
        ),
    ]
