# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0047_auto_20170206_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplies',
            name='down_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='commentreplies',
            name='rating',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='commentreplies',
            name='up_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='commentreplies',
            name='voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='r.Voter'),
        ),
        migrations.AddField(
            model_name='comments',
            name='down_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='up_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='r.Voter'),
        ),
    ]
