# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0048_auto_20170207_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
