# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0049_posttext_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttext',
            name='voted',
        ),
    ]
