# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='sender',
            new_name='author',
        ),
    ]
