# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20170122_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='body',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='recipient',
            field=models.CharField(max_length=30, verbose_name='to'),
        ),
    ]
