# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20170203_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
