# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmapoints',
            name='comment_karma',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='karmapoints',
            name='thread_karma',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
