# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0002_auto_20161116_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlink',
            name='subreddit',
        ),
        migrations.AddField(
            model_name='posttext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posttext',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='PostLink',
        ),
    ]
