# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0003_auto_20161118_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='rating_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='posttext',
            name='rating_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='posttext',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttext',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
