# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0005_auto_20161207_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='rating_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='posttext',
            name='rating_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
