# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('r', '0006_auto_20161207_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
