# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0009_auto_20161221_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttext',
            name='rating_dislikes',
        ),
        migrations.RemoveField(
            model_name='posttext',
            name='rating_likes',
        ),
        migrations.AddField(
            model_name='posttext',
            name='rating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
