# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0010_auto_20161222_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='has_voted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
