# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0017_auto_20161230_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='imgur_thumbnail',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
