# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0021_remove_posttext_imgur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='vote_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
