# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0024_auto_20170111_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttext',
            name='has_voted',
        ),
    ]
