# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0026_remove_posttext_vote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='r.Voter'),
        ),
    ]
