# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0032_privatemessage_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
