# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0033_auto_20170120_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
