# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0034_posttext_comments_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplies',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='r.Comments')),
                ('instance', models.IntegerField(default=0, editable=False)),
            ],
            bases=('r.comments',),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(verbose_name=''),
        ),
    ]
