# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0035_auto_20170203_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='default_instance',
            field=models.IntegerField(default=0),
        ),
    ]
