# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0042_commentreplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreplies',
            name='comments_ptr',
        ),
        migrations.RemoveField(
            model_name='commentreplies',
            name='reply_author',
        ),
        migrations.DeleteModel(
            name='CommentReplies',
        ),
    ]
