# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0051_posttext_is_promoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttext',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
