# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0052_auto_20170305_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscirbed',
            field=models.ManyToManyField(to='r.SubForum'),
        ),
    ]
